name: "LF Build Linux (aarch64)"

on:
  workflow_dispatch:
    inputs:
      package-version:
        description: 'The version ("major.minor.patch"). If empty, version is taken from `version.txt`, and revision is auto-incremented.'
        required: false
        default: ''
      lib-repo-ref:
        description: 'The branch, tag, or SHA to checkout from the lib repo. Defaults to the current branch or tag.'
        required: false
        default: ''
      distros:
        description: 'Comma-separated list of operating systems to build on. Supported: `debian11,debian12,rocky8,rocky9,ubuntu2004,ubuntu2204,ubuntu2404`.'
        required: false
        default: 'debian11,debian12,rocky8,rocky9,ubuntu2004,ubuntu2204,ubuntu2404'
      check-plugin:
        description: 'If you only want to compile a specific check plugin, specify its name, for example `cpu-usage`, otherwise leave empty to build all plugins.'
        required: false
        default: 'cpu-usage'

jobs:
  build-linux:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Print Inputs
        run: |
          echo "package-version: ${{ inputs.package-version }}"
          echo "lib-repo-ref: ${{ inputs.lib-repo-ref }}"
          echo "distros: ${{ inputs.distros }}"
          echo "check-plugin: ${{ inputs.check-plugin }}"
