name: 'Linuxfabrik: Build Linux (x86_64)'

on: [workflow_dispatch]

# modify the default permissions granted to the GITHUB_TOKEN
permissions:
  contents: 'read'

jobs:
  build-packages:
    runs-on:
      - 'ubuntu-24.04'
    steps:
      - uses: '${{ github.repository }}/lf-linux-build@8a8c7e1d4ca2d442ccffe73486c5c8bdbee59719'
