name: 'Linuxfabrik: Build Windows (x86_64)'

on:
  workflow_dispatch:
    inputs:
      package-version:
        description: 'The version ("major.minor.patch"). If empty, version is taken from `version.txt`, and revision is auto-incremented.'
        required: false
        default: ''
      lib-repo-ref:
        description: 'The branch, tag, or SHA to checkout from the lib repo. Defaults to the current branch or tag.'
        required: false
        default: ''
      check-plugin:
        description: 'If you only want to compile a specific check plugin, specify its name, for example `cpu-usage`, otherwise leave empty to build all plugins.'
        required: false
        default: 'cpu-usage'






jobs:
  build-windows:
    runs-on:
      - 'windows-2025'
    steps:
      - name: 'Print Inputs'
        run: |
          echo "package-version: ${{ inputs.package-version }}"
          echo "lib-repo-ref: ${{ inputs.lib-repo-ref }}"
          echo "check-plugin: ${{ inputs.check-plugin }}"

      - name: 'git clone https://github.com/Linuxfabrik/buildtest.git'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # v4.2.2

      - name: 'create list of windows checks'
        shell: 'bash'
        run: |
          build/shared/test.sh