name: "LF Controller Workflow"

on:
  workflow_dispatch:
    inputs:
      package-version:
        description: 'The version ("major.minor.patch"). If empty, version is taken from `version.txt`, and revision is auto-incremented.'
        required: false
        default: ''
      lib-repo-ref:
        description: 'The branch, tag or SHA to checkout from the lib repo. Defaults to the current branch or tag.'
        required: false
        default: ''
      distros:
        description: 'Comma-separated list of operating systems to build on. Supported: `debian11,debian12,rocky8,rocky9,ubuntu2004,ubuntu2204,ubuntu2404,windows`.'
        required: false
        default: 'debian11,debian12,rocky8,rocky9,ubuntu2004,ubuntu2204,ubuntu2404,windows'
      check-plugin:
        description: 'If you only want to compile a specific check plugin, specify its name, for example `cpu-usage`, otherwise leave empty to build all plugins.'
        required: false
        default: 'cpu-usage'
      arch:
        description: 'Comma-separated list of architectures to build on. Supported: `X64,ARM64`.'
        required: false
        default: 'X64,ARM64'

jobs:
  decide-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Workflows to Trigger
        run: |
          if echo "${{ inputs.distros }}" | grep -q "windows"; then
            echo "Triggering Windows Workflow"
            curl -X POST -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/lf-build-windows.yml/dispatches \
              -d '{
                "ref": "main",
                "inputs": {
                  "package-version": "${{ inputs.package-version }}",
                  "lib-repo-ref": "${{ inputs.lib-repo-ref }}",
                  "distros": "${{ inputs.distros }}",
                  "check-plugin": "${{ inputs.check-plugin }}",
                  "arch": "${{ inputs.arch }}"
                }
              }'
          fi

          if echo "${{ inputs.distros }}" | grep -vq "windows"; then
            echo "Triggering Linux Workflow"
            curl -X POST -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/lf-build-linux.yml/dispatches \
              -d '{
                "ref": "main",
                "inputs": {
                  "package-version": "${{ inputs.package-version }}",
                  "lib-repo-ref": "${{ inputs.lib-repo-ref }}",
                  "distros": "${{ inputs.distros }}",
                  "check-plugin": "${{ inputs.check-plugin }}",
                  "arch": "${{ inputs.arch }}"
                }
              }'
          fi
